version: '2.1'

services:
  banana-app:
    image: banana-app
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js